version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python main.py
    restart: always
    environment:
      - PYTHONUNBUFFERED=1